# using docker container
sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install flake8"
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install requests"
  - "pip install scrutinizer-ocular"
before_script:
  - export QINIU_ACCESS_KEY="QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm"
  - export QINIU_SECRET_KEY="Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz"
  - export QINIU_TEST_BUCKET="pythonsdk"
  - export QINIU_TEST_DOMAIN="pythonsdk.qiniudn.com"
  - export QINIU_TEST_ENV="travis"
  - export PYTHONPATH="$PYTHONPATH:."
script:
  - flake8 --show-source --show-pep8 --max-line-length=160 .
  - py.test --cov qiniu
  - ocular --data-file .coverage
